### ISSUE TITLE
Deploy protocol on testnet-1

### ISSUE THREAD

**Issue by Bal7hazar** [Carbonable/carbonable-starknet#113]
# Prerequis
Number of Projects: 7

Project 1 : Objective => quick Sold Out
- Name : Orang-StarkTest
- Symbol : 
- Image : 
- Max mint : 5
- Max  Supply : 15
- Reserve supply : 
- Token payment : ETH
- Description : 
- unit price : 
- Unit CO₂ sequestration : 
- Total CO₂ sequestration :
- Opening date  : 
- Whitelist open : false
- Open Public sale : true
- Years : 25

Project 2 : Objective => always open (very big supply)
- Name : Sea-StarkTest
- Symbol : 
- Image : 
- Max mint : 
- Max  Supply : 
- Reserve supply : 
- Token payment : ETH
- Description : 
- unit price : 
- Unit CO₂ sequestration : 
- Total CO₂ sequestration :
- Opening date  : 
- Whitelist open : false
- Open Public sale : true
- Years : 30 

Project 3 : Objectif => date de depart plus tard
- Name : Sunset-StarkTest
- Symbol : 
- Image : 
- Max mint : 
- Max  Supply : 
- Reserve supply : 
- Token payment : ETH
- Description : 
- unit price : 
- Unit CO₂ sequestration : 
- Total CO₂ sequestration :
- Opening date  : 
- Whitelist open : false
- Open Public sale : true
- Years : 28

Project 4 : Already Sold Out
- Name : Island-StarkTest
- Symbol : 
- Image : 
- Max mint : 
- Max  Supply : 
- Reserve supply : 
- Token payment : ETH
- Description : 
- unit price : 
- Unit CO₂ sequestration : 
- Total CO₂ sequestration :
- Opening date  : 
- Whitelist open : false
- Open Public sale : true
- Years : 22

Project 5 : Objective => buy at the same time (mint at the same time)
- Name : Swamp-StarkTest
- Symbol : 
- Image : 
- Max mint : 2
- Max  Supply : 5
- Reserve supply : 
- Token payment : ETH
- Description : 
- unit price : 
- Unit CO₂ sequestration : 
- Total CO₂ sequestration :
- Opening date  : 
- Whitelist open : false
- Open Public sale : true
- Years : 30

Project 6 : Objective => Project shared between B2B and B2C
- Name : Croco-StarkTest
- Symbol : 
- Image : 
- Max mint : 
- Max  Supply : 100 000
- Reserve supply : 99 000
- Token payment : ETH
- Description : 
- unit price : 
- Unit CO₂ sequestration : 
- Total CO₂ sequestration :
- Opening date  : 
- Whitelist open : false
- Open Public sale : true
- Years : 20

Project 7 : Objective => The Project has a Max supply = Reserve supply
- Name : Jaguar-StarkTest
- Symbol : 
- Image : 
- Max mint : 
- Max  Supply : 10 000
- Reserve supply : 10 000
- Token payment : ETH
- Description : 
- unit price : 
- Unit CO₂ sequestration : 
- Total CO₂ sequestration :
- Opening date  : 
- Whitelist open : false
- Open Public sale : true
- Years : 27

**Comment by G2CARBZ** [comment]
**Generic description** (to apply to all)

*For testing purposes only!* 
This collection of NFTs is part of Carbonable's DeFi protocol test series. Come join our growing community of green pioneers! Carbonable's mission is to align the best interests of investors and the planet. 
We empower anyone to invest in the greatest challenge of our time, by financing nature’s regeneration, while getting a high growing yield. 
*Launching soon on mainnet, be ready!*

**Comment by G2CARBZ** [comment]
Table with all the data + NFTs in this drive:
https://drive.google.com/drive/folders/1KeenhBilF0D-35aXwpDxJq82RPGfn-9t

**Comment by Bal7hazar** [comment]
# Protocol Testnet-1

## 1. Orang-StarkTest

### Contracts



## 2. Sea-StarkTest

### Contracts

[Project](https://testnet.starkscan.co/contract/0x5a85cf2c715955a5d8971e01d1d98e04c31d919b6d59824efb32cc72ae90e63)
[Minter](https://testnet.starkscan.co/contract/0x1607f07db4c365c374c157d1c894c2b53dd1b59ca5509f9f5821bdd1bfa0cb0)
[Vester](https://testnet.starkscan.co/contract/0x7aa454887b454d69c352c80f2067426b26b1af4f6b17f2141773fbe65d16d0c)
[Offseter](https://testnet.starkscan.co/contract/0x27476cd4bcac6c3a8428dc258acac7e7ccd765aabcc366fe4fb37e6b3fe0987)
[Yielder](https://testnet.starkscan.co/contract/0x5d111e5be6a71f11949f20450ba436d2e04789a9e8a3caed0e78444f74c9ef7)

### Preview

- [Mintsquare](https://mintsquare.io/collection/starknet-testnet/0x05a85cf2c715955a5d8971e01d1d98e04c31d919b6d59824efb32cc72ae90e63)
- [Aspect](https://testnet.aspect.co/collection/0x05a85cf2c715955a5d8971e01d1d98e04c31d919b6d59824efb32cc72ae90e63)

## 3. Sunset-StarkTest

### Contracts



## 4. Island-StarkTest

### Contracts



## 5. Swamp-StarkTest

### Contracts



## 6. Croco-StarkTest

### Contracts



## 7. Jaguar-StarkTest

### Contracts

**Comment by Bal7hazar** [comment]
Here are the [abi.zip](https://github.com/Carbonable/carbonable-starknet/files/10206012/abi.zip) files.
