### ISSUE TITLE
Deploy the Badge v2 on Alpha-mainnet

### ISSUE THREAD

**Issue by cloudvenger** [Carbonable/carbonable-starknet#127]
**Description**
---
Deploy the Badge v2 (with Minter & Badge project with Proxy) on Alpha-mainnet

**Prerequis**
---
The admin wallet have to be created on alpha-mainnet.
Issue: #130 #125 

**Acceptance Criteria**
---

- [ ]  A Badge is claim and can be vizualised on marketplaces

**Additional context**
---

Protocol Alpha-mainet
Badge information
Contracts
[Badge]
[Minter]

Image

Preview

**Comment by Bal7hazar** [comment]
Badge - [0x372ed7c5e187c84994a804d343adb70d3394a9269d398d04e6991e8c6cd7939](https://alpha-mainnet.starkscan.co/contract/0x372ed7c5e187c84994a804d343adb70d3394a9269d398d04e6991e8c6cd7939)

Minter - [0x4b13fd9300bf4dbd94a3434455551e3beb424aebfd41962839d60b53a4590b2](https://alpha-mainnet.starkscan.co/contract/0x4b13fd9300bf4dbd94a3434455551e3beb424aebfd41962839d60b53a4590b2)
