### ISSUE TITLE
reserved supply update

### ISSUE THREAD

**Issue by Bal7hazar** [Carbonable/carbonable-starknet#31]
To handle the case where some reserved spots won't be minted due to unexpected events (such as B2B withdrawal).

As an admin, we want the ability to move some slots from reserved supply into public supply.

To proceed, we need to be able to decrease the reserved supply (only decrease).

Three scenarios:

## 1. :tada: 

```cairo
set_reserved_supply_for_mint(reserved_supply_for_mint : felt)
```
Which fails if the new reserved_supply_for_mint is `ge` to the stored one

Note: less explicit name, easier to use since math are done by the contract

## 2. :heart: 

```cairo
decrease_reserved_supply_for_mint(slots : felt)
```
Which fails if `slots` is `gt` than  the stored one

Note: more explicit name, admin needs to ensure math before the usage

## 3. :rocket:

```cairo
set_decreased_reserved_supply_for_mint(reserved_supply_for_mint : felt)
```
Which fails if the new reserved_supply_for_mint is `ge` to the stored one

Note: name too long?

**Comment by abdelhamidbakhta** [comment]
I am personally for the more explicit name: `decrease_reserved_supply_for_mint `

**Comment by Bal7hazar** [comment]
> I am personally for the more explicit name: `decrease_reserved_supply_for_mint `

Imo the most explicit one is : `set_decreased_reserved_supply_for_mint(reserved_supply_for_mint : felt)`

Just to ensure we are in phase, 

The scenario # 2 :heart: is about to substract the stored value with the 'slots' number provided:

```bash
anyone.reserved_supply_for_mint()  # 15
admin.decrease_reserved_supply_for_mint(5)
anyone.reserved_supply_for_mint()  # 10
```

Where scenario # 3 :rocket: is about to store the provided value:

```bash
anyone.reserved_supply_for_mint()  # 15
admin.set_decreased_reserved_supply_for_mint(10)
anyone.reserved_supply_for_mint()  # 10
```
