### ISSUE TITLE
Test refactoring

### ISSUE THREAD

**Issue by Bal7hazar** [Carbonable/carbonable-starknet#40]
# Proposition

The propopsition is mainly motivated by the growth of new features and SOC.
Since we are adding more and more contracts and features, it could be interesting to refactor tests.

## Integration tests

Integration tests focus on nominal usages by default, this is what aim the test_nominal_cases files of each contract.

We also want to test specific behaviors by chaining actions between contracts, this will be the purpose of the test_specific_cases file of each contract.

Notes:
- I think protostar generate a single instance of what the `__setup__` returns **for each test files** which could slow down tests and increase memory usage
- we need to check how to factorize the `__setup__` cheatcode

## Unit tests

Unit tests focus on the nominal cases and expect revert tests, since several tests are required per new functionnality (according to the number of exception raised by the function), there is an opportunity to spread tests per functionnality.

Note: A new library.cairo file could store shared code (as the one in the integration tests).

## Folder structure diagram

```
tests/
├── integrations/
│   ├── library.cairo
│   ├── minter/
│   │   └── test_nominal_cases.cairo
│   │   └── test_specific_cases.cairo
│   ├── yielder/
│   │   └── test_nominal_cases.cairo
│   │   └── test_specific_cases.cairo
│   ├── .../
├── mocks/
│   └── erc20.cairo
├── units/
│   ├── library.cairo
│   ├── minter/
│   │   ├── test_decrease_reserved_supply_for_mint.cairo
│   │   ├── test_...
│   │   ├── test_airdrop.cairo
│   │   ├── test_whitelist_buy.cairo
│   │   └── test_public_buy.cairo
│   ├── yielder/
│   │   └── test_...
```

**Comment by Bal7hazar** [comment]
@abdelhamidbakhta @cloudvenger, what do you think about the proposition?

**Comment by abdelhamidbakhta** [comment]
> @abdelhamidbakhta @cloudvenger, what do you think about the proposition?

Looks good to me.

**Comment by cloudvenger** [comment]
Perfect for me, I prefer like you propose, to split by business features
