### ISSUE TITLE
IERC20 transferFrom call

### ISSUE THREAD

**Issue by Bal7hazar** [Carbonable/carbonable-starknet#9]
I don't understand why the following code is actually working:

Here is the `IERC20`  contract from openzepplin depencency:

```cairo
@external
func transferFrom{
        syscall_ptr : felt*,
        pedersen_ptr : HashBuiltin*,
        range_check_ptr
    }(
        sender: felt,
        recipient: felt,
        amount: Uint256
    ) -> (success: felt):
    ERC20.transfer_from(sender, recipient, amount)
    return (TRUE)
```

And here is a call of the ` transferFrom`  function from [here](https://github.com/Carbonable/carbonable-starknet/blob/main/src/mint/library.cairo#L262) in the mint contract regarding the payment during the ` buy` function.

```cairo
# Do ERC20 transfer
let (transfer_success) = IERC20.transferFrom(
    payment_token_address, caller, contract_address, amount
)
```

So basically there are 4 arguments provided where IERC20 expects 3, but actually tests works so I'm probably misunderstanding something.

**Comment by abdelhamidbakhta** [comment]
Basically when you call a smart contract through the interface the first parameter is the address of the smart contract implementing the interface
